pub type OpCode = u8;

// NOTE: remember to add this value to proper *Instr array below
#[derive(FromPrimitive, Debug)]
pub enum OpCodeValue {
    Lr = 0x00,
    Lnr = 0x01,
    Str = 0x02,
    Swapr = 0x03,
    Andr = 0x04,
    Orr = 0x05,
    Xorr = 0x06,
    Notr = 0x07,
    Bcsr = 0x08,
    Bcrr = 0x09,
    Balr = 0x0a,
    Sacr = 0x0b,
    Ar = 0x10,
    Sr = 0x11,
    Rsr = 0x12,
    Mr = 0x13,
    Dr = 0x14,
    Rdr = 0x15,
    Remr = 0x16,
    Rremr = 0x17,
    L = 0x20,
    St = 0x22,
    Swap = 0x23,
    And = 0x24,
    Or = 0x25,
    Xor = 0x26,
    Not = 0x27,
    Svc = 0x2e,
    A = 0x30,
    S = 0x31,
    Rs = 0x32,
    M = 0x33,
    D = 0x34,
    Rd = 0x35,
    Rem = 0x36,
    Rrem = 0x37,
    Li = 0x40,
    Andi = 0x44,
    Ori = 0x45,
    Xori = 0x46,
    Noti = 0x47,
    Ai = 0x50,
    Si = 0x51,
    Rsi = 0x52,
    Mi = 0x53,
    Di = 0x54,
    Rdi = 0x55,
    Remi = 0x56,
    Rremi = 0x57,
    Andc = 0x64,
    Orc = 0x65,
    Xorc = 0x66,
    Notc = 0x67,
    Ac = 0x70,
    Sc = 0x71,
    Rsc = 0x72,
    Mc = 0x73,
    Dc = 0x74,
    Rdc = 0x75,
    Remc = 0x76,
    Rremc = 0x77,
    Min = 0x7a,
    Max = 0x7b,
}

pub enum OpType {
    Rr,
    Rrm,
    Rs,
    Im,
    Ch,
}

pub static RR_INSTR: &'static [OpCode] = &[
    OpCodeValue::Lr as OpCode,
    OpCodeValue::Lnr as OpCode,
    OpCodeValue::Swapr as OpCode,
    OpCodeValue::Str as OpCode,
    OpCodeValue::Andr as OpCode,
    OpCodeValue::Orr as OpCode,
    OpCodeValue::Xorr as OpCode,
    OpCodeValue::Notr as OpCode,
    OpCodeValue::Balr as OpCode,
    OpCodeValue::Ar as OpCode,
    OpCodeValue::Sr as OpCode,
    OpCodeValue::Rsr as OpCode,
    OpCodeValue::Mr as OpCode,
    OpCodeValue::Dr as OpCode,
    OpCodeValue::Rdr as OpCode,
    OpCodeValue::Remr as OpCode,
    OpCodeValue::Rremr as OpCode,
];
pub static RRM_INSTR: &'static [OpCode] = &[
    OpCodeValue::Bcsr as OpCode,
    OpCodeValue::Bcrr as OpCode,
    OpCodeValue::Sacr as OpCode,
];
pub static RS_INSTR: &'static [OpCode] = &[
    OpCodeValue::L as OpCode,
    OpCodeValue::St as OpCode,
    OpCodeValue::Swap as OpCode,
    OpCodeValue::Svc as OpCode,
    OpCodeValue::And as OpCode,
    OpCodeValue::Or as OpCode,
    OpCodeValue::Xor as OpCode,
    OpCodeValue::Not as OpCode,
    OpCodeValue::A as OpCode,
    OpCodeValue::S as OpCode,
    OpCodeValue::Rs as OpCode,
    OpCodeValue::M as OpCode,
    OpCodeValue::D as OpCode,
    OpCodeValue::Rd as OpCode,
    OpCodeValue::Rem as OpCode,
    OpCodeValue::Rrem as OpCode,
    OpCodeValue::Min as OpCode,
    OpCodeValue::Max as OpCode,
];
pub static IM_INSTR: &'static [OpCode] = &[
    OpCodeValue::Li as OpCode,
    OpCodeValue::Andi as OpCode,
    OpCodeValue::Ori as OpCode,
    OpCodeValue::Xori as OpCode,
    OpCodeValue::Noti as OpCode,
    OpCodeValue::Ai as OpCode,
    OpCodeValue::Si as OpCode,
    OpCodeValue::Rsi as OpCode,
    OpCodeValue::Mi as OpCode,
    OpCodeValue::Di as OpCode,
    OpCodeValue::Rdi as OpCode,
    OpCodeValue::Remi as OpCode,
    OpCodeValue::Rremi as OpCode,
];
pub static CH_INSTR: &'static [OpCode] = &[
    OpCodeValue::Andc as OpCode,
    OpCodeValue::Orc as OpCode,
    OpCodeValue::Xor as OpCode,
    OpCodeValue::Notc as OpCode,
    OpCodeValue::Ac as OpCode,
    OpCodeValue::Sc as OpCode,
    OpCodeValue::Rsc as OpCode,
    OpCodeValue::Mc as OpCode,
    OpCodeValue::Dc as OpCode,
    OpCodeValue::Rdc as OpCode,
    OpCodeValue::Remc as OpCode,
    OpCodeValue::Rremc as OpCode,
];
